name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Compile contracts
        run: npm run compile
        
      - name: Run tests
        run: npm test
        
      - name: Run L1 tests
        run: npm run test:l1
        
      - name: Run L2 tests
        run: npm run test:l2
        
      - name: Generate gas report
        run: npm run test:gas
        env:
          REPORT_GAS: true

  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Lint Solidity files
        run: npm run lint:sol
        continue-on-error: true
        
      - name: Lint JavaScript files
        run: npm run lint:js
        continue-on-error: true

  security:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run security audit
        run: npm audit --audit-level moderate
        continue-on-error: true
        
      - name: Install Slither
        run: |
          pip3 install slither-analyzer
          
      - name: Run Slither analysis
        run: |
          slither contracts/ --print human-summary || true
        continue-on-error: true

  coverage:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Generate coverage report
        run: npm run test:coverage
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests
          name: tokenbot-coverage
          fail_ci_if_error: false

  build-validation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Clean build artifacts
        run: npm run clean
        
      - name: Compile contracts
        run: npm run compile
        
      - name: Validate contract sizes
        run: npm run size
        continue-on-error: true
        
      - name: Check for compilation warnings
        run: |
          npm run compile 2>&1 | tee compile.log
          if grep -i "warning" compile.log; then
            echo "⚠️ Compilation warnings found"
            exit 1
          fi
        continue-on-error: true

  dependencies:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Check for outdated dependencies
        run: npm outdated || true
        
      - name: Check for vulnerable dependencies
        run: npm audit --audit-level high
        continue-on-error: true